name = "visx-vue-demo"
main = ".output/server/index.mjs"
compatibility_date = "2025-07-14"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".output/public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "visx-demo"
database_id = "485cf5aa-c730-4704-a3a6-c052cc0466dc"

[[routes]]
pattern = "nuxtcharts.com/visx-vue"
zone_name = "nuxtcharts.com"

[[routes]]
pattern = "nuxtcharts.com/visx-vue/*"
zone_name = "nuxtcharts.com"

[observability]
enabled = true
